name = "wk-bpb-auto-update"
main = "_worker.js"
compatibility_date = "2024-04-28"
workers_dev = false

[[kv_namespaces]]
binding = "kv"
id = "56716a45f8764a67960d9dc7eacc40f0"

[vars]
UUID= "d3129df7-1eb7-4eba-a12f-79775c1936f9"
TR_PASS = "8f01b439-e47f-47f2-86b9-ed77034cbf2d"
