name = "wk-bp"
main = "_worker.js"
compatibility_date = "2026-03-12"
no_bundle = true
workers_dev = true
preview_urls = true


[[kv_namespaces]]
binding = "kv"
#修改为自己创建的kv id
id = "56716a45f8764a67960d9dc7eacc40f0"

[vars]
# 修改为自己的
UUID = "2475721d-a490-42d6-9255-cd1bddfb805d"
TR_PASS = "Z5D@r44gzK#@Bd2!"
FALLBACK="www.speedtest.net"


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true