name = "wk-bpb"
main = "_worker.js"
compatibility_date = "2024-04-28"
workers_dev = true
preview_urls = true


[[kv_namespaces]]
binding = "kv"
#修改为自己创建的kv id
id = "56716a45f8764a67960d9dc7eacc40f0"

[vars]
# 修改为自己的
UUID = "2475721d-a490-42d6-9255-cd1bddfb805d"
TR_PASS = "157a9dd6-54fc-4228-aeac-8ff9676d074f"


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true